---
- name: clear rails cache
  command: bundle exec rake tmp:cache:clear
  args:
    chdir: '{{ project_app_root }}'
  notify:
    - precompile assets
    - restart nginx
  become: yes
  become_user: '{{ project_owner }}'
  environment:
    RAILS_ENV: '{{ project_app_env }}'

- name: precompile assets
  command: bundle exec rails assets:precompile
  args:
    chdir: '{{ project_app_root }}'
  when: project_app_env == 'production'
  notify: restart nginx
  become: yes
  become_user: '{{ project_owner }}'
  environment:
    RAILS_ENV: '{{ project_app_env }}'

- name: restart resque
  service:
    name: resque-pool
    state: restarted
  become: yes

- name: restart sidekiq workers
  service:
    name: "{{ sidekiq_service }}"
    state: restarted
  become: yes
