---
- name: add the project group for the application
  group:
    name: '{{ project_group }}'
    system: '{{ project_group_system }}'
    gid: '{{ project_group_id | default(omit) }}'

- name: create the project user with no login password
  user:
    name: '{{ project_user }}'
    group: '{{ project_group }}'
    home: '{{ project_user_home }}'
