---
- block:
  - name: load workflow
    command: ./bin/rails hyrax:workflow:load
    args:
      chdir: '{{ project_app_root }}'
  # - name: create default admin set
  #   command: ./bin/rails hyrax:default_admin_set:create
  #   args:
  #     chdir: '{{ project_app_root }}'
  - name: create roles
    command: ./bin/rails binaryarts:add_roles
    args:
      chdir: '{{ project_app_root }}'

  - name: copy list of admins
    copy:
      src: "{{ local_files_dir }}/admin_list.txt"
      dest: '{{ project_app_root }}/admin_list.txt'
    ignore_errors: True
    register: copy_admin_list

  - name: upgrade users
    command: ./bin/rails binaryarts:upgrade_users
    args:
      chdir: '{{ project_app_root }}'
    when: copy_admin_list|succeeded

  become: yes
  become_user: '{{ project_owner }}'
  environment:
    RAILS_ENV: '{{ project_app_env }}'
