---
- block:
  - name: load workflow
    command: ./bin/rails hyrax:workflow:load
    args:
      chdir: '{{ project_app_root }}'
  # - name: create default admin set
  #   command: ./bin/rails hyrax:default_admin_set:create
  #   args:
  #     chdir: '{{ project_app_root }}'

  become: yes
  become_user: '{{ project_owner }}'
  environment:
    RAILS_ENV: '{{ project_app_env }}'
