---
- block:
  - name: add carousel images
    command: bundle exec rake iawa:update_images['{{ project_app_root }}/vendor/assets/images/iawa.zip']
    args:
      chdir: '{{ project_app_root }}'

  - name: add initial controlled vocabularies
    command: bundle exec rake iawa:add_controlled_vocabs
    args:
      chdir: '{{ project_app_root }}'

  become: yes
  become_user: '{{ project_owner }}'
  environment:
    RAILS_ENV: '{{ project_app_env }}'
