- name: copy sidekiq init scripts
  template:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items: "{{ sidekiq_service_files }}"
  notify:
    - restart redis
    - restart sidekiq workers

- name: ensure sidekiq runs at startup
  service:
    name: "{{ sidekiq_service }}"
    enabled: yes
