- name: copy sidekiq init scripts
  template:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - file: sidekiq.service.j2
      dest: /lib/systemd/system/sidekiq.service
  notify:
    - restart redis
    - restart sidekiq workers

- name: ensure sidekiq runs at startup
  service:
    name: sidekiq
    enabled: yes
