---
- block:
  - name: create sufia solr core
    file:
      path: '{{ solr_data_dir }}/{{ project_solr_core }}/conf'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      state: directory
  - name: ensure core name in core.properties
    lineinfile:
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/core.properties'
      line: name={{ project_solr_core }}
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      create: True
    notify: restart solr
  - name: copy hyrax's solrconfig.xml to the core
    copy:
      src: '{{ project_app_root }}/solr/conf/solrconfig.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/solrconfig.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_solrconfig
    ignore_errors: True
  - name: copy sufia's solrconfig.xml to the core
    copy:
      src: '{{ project_app_root }}/solr/config/solrconfig.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/solrconfig.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    when: hyrax_solrconfig is failed
    register: solrconfig
    ignore_errors: True
  - name: copy sufia's solrconfig.xml to the core from a legacy location
    copy:
      src: '{{ project_app_root }}/solr_conf/conf/solrconfig.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/solrconfig.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    when: solrconfig is failed
  - name: copy hyrax's schema.xml to the core
    copy:
      src: '{{ project_app_root }}/solr/conf/schema.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/schema.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_schema
    ignore_errors: True
  - name: copy sufia's schema.xml to the core
    copy:
      src: '{{ project_app_root }}/solr/config/schema.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/schema.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    when: hyrax_schema is failed
    register: schema
    ignore_errors: True
  - name: copy sufia's schema.xml to the core from a legacy location
    copy:
      src: '{{ project_app_root }}/solr_conf/conf/schema.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/schema.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    when: schema is failed

  - name: copy hyrax's synonyms.txt to the core
    copy:
      src: '{{ project_app_root }}/solr/conf/synonyms.txt'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/synonyms.txt'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_solr_synonyms
    ignore_errors: True

  - name: copy hyrax's protwords.txt to the core
    copy:
      src: '{{ project_app_root }}/solr/conf/protwords.txt'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/protwords.txt'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_solr_protwords
    ignore_errors: True

  - name: copy hyrax's stopwords_en.txt to the core
    copy:
      src: '{{ project_app_root }}/solr/conf/stopwords_en.txt'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/stopwords_en.txt'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_solr_stopwords_en
    ignore_errors: True

  - name: copy hyrax's stopwords.txt to the core
    copy:
      src: '{{ project_app_root }}/solr/conf/stopwords.txt'
      dest: '{{ solr_data_dir }}/{{ project_solr_core }}/conf/stopwords.txt'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_solr_stopwords
    ignore_errors: True

- block:
  - name: create sufia solr test core
    file:
      path: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      state: directory
  - name: ensure test core name in core.properties
    lineinfile:
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/core.properties'
      line: name={{ project_solr_test_core }}
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      create: True
    notify: restart solr
  - name: copy hyrax's solrconfig.xml to the test core
    copy:
      src: '{{ project_app_root }}/solr/conf/solrconfig.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/solrconfig.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_test_solrconfig
    ignore_errors: True
  - name: copy sufia's solrconfig.xml to the test core
    copy:
      src: '{{ project_app_root }}/solr/config/solrconfig.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/solrconfig.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    when: hyrax_test_solrconfig is failed
    register: test_solrconfig
    ignore_errors: True
  - name: copy sufia's solrconfig.xml to the test core from a legacy location
    copy:
      src: '{{ project_app_root }}/solr_conf/conf/solrconfig.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/solrconfig.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    when: test_solrconfig is failed
  - name: copy hyrax's schema.xml to the test core
    copy:
      src: '{{ project_app_root }}/solr/conf/schema.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/schema.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_test_schema
    ignore_errors: True
  - name: copy sufia's schema.xml to the test core
    copy:
      src: '{{ project_app_root }}/solr/config/schema.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/schema.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    when: hyrax_test_schema is failed
    register: test_schema
    ignore_errors: True
  - name: copy sufia's schema.xml to the test core from a legacy location
    copy:
      src: '{{ project_app_root }}/solr_conf/conf/schema.xml'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/schema.xml'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    when: test_schema is failed
  - name: copy hyrax's synonyms.txt to the test core
    copy:
      src: '{{ project_app_root }}/solr/conf/synonyms.txt'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/synonyms.txt'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_test_solr_synonyms
    ignore_errors: True
  - name: copy hyrax's protwords.txt to the test core
    copy:
      src: '{{ project_app_root }}/solr/conf/protwords.txt'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/protwords.txt'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_test_solr_protwords
    ignore_errors: True

  - name: copy hyrax's stopwords_en.txt to the test core
    copy:
      src: '{{ project_app_root }}/solr/conf/stopwords_en.txt'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/stopwords_en.txt'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_test_solr_stopwords_en
    ignore_errors: True

  - name: copy hyrax's stopwords.txt to the test core
    copy:
      src: '{{ project_app_root }}/solr/conf/stopwords.txt'
      dest: '{{ solr_data_dir }}/{{ project_solr_test_core }}/conf/stopwords.txt'
      owner: '{{ solr_user }}'
      group: '{{ solr_group }}'
      mode: 0444
      remote_src: True
    notify: restart solr
    register: hyrax_test_solr_stopwords
    ignore_errors: True


  when: project_app_env == 'development'
