---
- name: add Brightbox repository
  apt_repository:
    repo: 'ppa:brightbox/ruby-ng'
    update_cache: yes
    state: present

- name: install Brightbox Ruby package
  apt:
    name:
      - ruby{{ ruby_version | default('2.3') }}
      - ruby{{ ruby_version | default('2.3') }}-dev
    state: present
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes

- name: install bundler
  gem:
    name: bundler
    state: latest
    user_install: no
