# vi: set ft=ruby :

installuser = "vagrant"
hydrahead = "data-repo"
gitrepo = "VTUL/" + hydrahead

runserver = <<EOF
cd "/home/$1/$2/"
bundle exec rake jetty:start
# Assume CAS_extras.sh has been run
bash ./scripts/restart_resque.sh production
echo "The server should be running at localhost:8080"
echo "If you generated a certificate, you can also use https://localhost:4433"
echo "The site exists in /home/$1/$2"
EOF

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'data-repo-dev'
    vb.cpus = 2
    vb.memory = 2048
  end
  config.vm.network :forwarded_port, host: 3000, guest: 3000
  config.vm.network :forwarded_port, host: 8080, guest: 8080
  config.vm.network :forwarded_port, host: 4433, guest: 4433
  config.vm.provision :shell, args: [installuser, hydrahead, gitrepo], privileged: true,
    path: 'bootstrap.sh'
  config.vm.provision :shell, args:[installuser, hydrahead], run: 'always', privileged: false, inline: runserver
end
