 vi: set ft=ruby :

hydrahead = "data-repo"
gitrepo = "VTUL/" + hydrahead

runserver = <<EOF
cd "/home/vagrant/$1/"
bundle exec rake jetty:start
PIDFILE=/home/vagrant/$1/tmp/pids/resque.pid BACKGROUND=yes QUEUE=* rake environment resque:work \
  1> /home/vagrant/$1/log/resque.log 2> /home/vagrant/$1/log/resque.log
bundle exec rails server --binding=0.0.0.0 --daemon
echo "The server should be running at 127.0.0.1:3000"
echo "The site exists in /home/vagrant/$1"
EOF

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'data-repo-dev'
    vb.cpus = 2
    vb.memory = 2048
  end
  config.vm.network :forwarded_port, host: 3000, guest: 3000
  config.vm.provision :shell, args: [hydrahead, gitrepo], privileged: false,
    path: 'https://raw.githubusercontent.com/VTUL/InstallScripts/master/Vagrant/bootstrap.sh'
  config.vm.provision :shell, args:[hydrahead], run: 'always', privileged: false, inline: runserver
end
