# vi: set ft=ruby :

installuser = "vagrant"
hydrahead = "data-repo"
gitrepo = "VTUL/" + hydrahead
server_hostname = "localhost"

runserver = <<EOF
cd "/home/$1/$2/"
bundle exec rake jetty:start
bash ./scripts/restart_resque.sh production
sudo service nginx restart
echo "The server should be running at localhost:8080"
echo "(You can also use https://localhost:4443)"
echo "The application exists in /home/$1/$2"
EOF

Vagrant.configure(2) do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'data-repo-dev'
    vb.cpus = 2
    vb.memory = 2048
  end
  config.vm.network :forwarded_port, host: 8983, guest: 8983
  config.vm.network :forwarded_port, host: 8080, guest: 80
  config.vm.network :forwarded_port, host: 4443, guest: 443
  config.vm.provision :shell, args: [installuser, hydrahead, gitrepo, server_hostname],
    privileged: true, path: 'bootstrap.sh'
  config.vm.provision :shell, args:[installuser, hydrahead], run: 'always', privileged: false, inline: runserver
end
