---
- name: install clamav
  apt:
    name: '{{ item }}'
    state: present
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes
  with_items:
    - clamav
    - libclamav-dev

- name: use local private mirror if enabled
  lineinfile:
    dest: /etc/clamav/freshclam.conf
    insertafter: EOF
    line: PrivateMirror {{ clamav_private_mirror_host }}
    state: present
  when: clamav_private_mirror_enabled

- name: disable local private mirror if not enabled
  lineinfile:
    dest: /etc/clamav/freshclam.conf
    regexp: "PrivateMirror .*"
    state: absent
  when: not clamav_private_mirror_enabled

- name: stop clamav so that manual database update can happen
  service:
    name: clamav-freshclam
    state: stopped

- name: create/update the clamav databases
  command: /usr/bin/freshclam --quiet
  register: freshclam_cmd
  failed_when: freshclam_cmd.rc > 1

- name: start clamav and enable to run at boot
  service:
    name: clamav-freshclam
    state: started
    enabled: yes
