---

- name: import nodesource GPG key
  become: yes
  shell: /usr/bin/curl https://deb.nodesource.com/gpgkey/nodesource.gpg.key | /usr/bin/apt-key add -

- name: add nodesource deb repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
    state: present

- name: install nodejs
  apt:
    name: nodejs
    state: present
    update_cache: yes
