---
- name: import nodesource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    state: present

- name: add nodesource deb repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ nodejs_version }} {{ ansible_distribution_release }} main'
    state: present
    update_cache: yes

- name: install nodejs
  apt:
    name: nodejs
    state: present
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes
