---
- name: set postfix mailer type and hostname
  debconf:
    name: postfix
    question: '{{ item.question }}'
    value: '{{ item.value }}'
    vtype: string
  with_items:
    - question: postfix/main_mailer_type
      value: "'Internet Site'"
    - question: postfix/mailname
      value: '{{ ansible_fqdn }}'

- name: install postfix application
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  with_items:
    - postfix
    - mailutils

- name: set postfix listening interfaces
  lineinfile:
    dest: /etc/postfix/main.cf
    regexp: '^inet_interfaces = .*$'
    line: 'inet_interfaces = {{ postfix_inet_interfaces }}'
  notify: restart postfix
