---
ansible_user: 'vagrant'
project_name: 'data-repo'
project_user: 'hydra'
project_user_home: '/var/local/{{ project_user }}'
project_group: '{{ project_user }}'
project_group_system: 'no'
project_group_id: ''
project_git_url: 'https://github.com/VTUL/{{ project_name }}.git'
project_git_branch: 'master'
project_deploy_key: ''
project_app_env: 'production'
project_app_root: '{{project_user_home }}/{{ project_name }}'
project_geonames_user: ''
project_ezid_shoulder: 'doi:10.5072/FK2'
project_ezid_user: 'apitest'
project_ezid_password: 'apitest'
project_orcid_app_id: '0000-0000-0000-0000'
project_orcid_app_secret: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
project_db_name: 'datarepo'
project_db_user: '{{ project_user }}'
project_db_password: 'changeme'
project_solr_url: 'http://localhost:8983/solr'
project_solr_core: '{{ project_app_env }}'
project_solr_test_core: 'test'
project_fedora_url: 'http://127.0.0.1:8080/fedora/rest'
project_fedora_user: 'fedoraAdmin'
project_fedora_password: 'fedoraAdmin'
project_fedora_base_path: '/prod'
project_redis_host: 'localhost'
project_redis_port: '6379'
project_cas_url: 'https://login-dev.middleware.vt.edu/profile/cas'
project_secret_key_base: ''
solr_user: 'solr'
solr_group: '{{ solr_user }}'
solr_data_dir: '/var/solr/data'
database_user: 'postgres'
database_group: 'postgres'
database_password: 'postgres'
