---
- name: ensure tomcat7 packages are installed
  apt:
    name: ['tomcat7', 'tomcat7-admin']
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes
    state: present

- name: copy tomcat 7 config file
  template:
    src: server.xml.j2
    dest: /etc/tomcat7/server.xml
    mode: 0644

- name: add line to specify java_home
  lineinfile:
    dest: /etc/default/tomcat7
    line: "JAVA_HOME=/usr/lib/jvm/java-8-{{'openjdk-amd64' if java_vendor == 'openjdk' else 'oracle'}}"

- name: ensure tomcat7 starts on boot
  service:
    name: tomcat7
    enabled: yes
