---
fedora_user: '{{ tomcat_user }}'
fedora_group: '{{ fedora_user }}'
fedora_user_home: '/var/local/{{ fedora_user }}'
fedora_data_dir: '{{ fedora_user_home }}/fedora-data'
fedora_app_dir: '/var/lib/{{ tomcat_user }}/webapps'
fedora_java_vm_opts: "{{ project_fedora_java_vm_opts | default('-Xms512m -Xmx1024m -XX:NewSize=256m -XX:MaxNewSize=256m -XX:MetaspaceSize=256m -XX:MaxMetaspaceSize=256m -XX:+DisableExplicitGC') }}"
