---
- name: make sure project user owns application
  file:
    path: "{{ project_app_root }}"
    mode: "0755"
    owner: "{{ project_user }}"
    group: "{{ project_group }}"
    state: directory
    recurse: yes

- name: clone the geoblacklight repo
  git:
    repo: "{{ project_git_url }}"
    dest: "{{ project_app_root }}"
    version: "{{ project_git_identifier }}"
    force: yes
  become_user: "{{ project_user }}"

- name: copy the secrets file
  template:
    src: secrets.yml.j2
    dest: "{{ project_app_root }}/config/secrets.yml"
    owner: "{{ project_user }}"
    group: "{{ project_group }}"
    mode: "0440"

- name: install production gems
  bundler:
    state: present
    chdir: "{{ project_app_root }}"
    exclude_groups: 'development test'
    user_install: no
  environment:
    RAILS_ENV: '{{ project_app_env }}'
  when: project_app_env == "production"

- name: install development gems
  bundler:
    state: present
    chdir: "{{ project_app_root }}"
    user_install: no
  environment:
    RAILS_ENV: '{{ project_app_env }}'
  when: project_app_env != "production"

- name: load db schema
  command: bundle exec rake db:setup
  args:
    chdir: "{{ project_app_root }}"
  environment:
    RAILS_ENV: '{{ project_app_env }}'
  become_user: '{{ project_user }}'

- name: precompile
  command: bundle exec rake assets:precompile
  args:
    chdir: "{{ project_app_root }}"
  environment:
    RAILS_ENV: '{{ project_app_env }}'
  become_user: '{{ project_user }}'
  when: project_app_env == "production"
