---
- name: install common rails dependencies
  apt:
    name: ['git', 'sqlite3', 'libsqlite3-dev', 'zlib1g-dev']
    state: present
    cache_valid_time: '{{ apt_cache_timeout }}'
    update_cache: yes

- name: geoblacklight requires a newer version of RubyGems
  command: gem update --system

- include: nginx_setup.yml
- include: geoblacklight_setup.yml
- include: solr_setup.yml
- include: cron.yml

- name: restart ruby applications when ruby version changed
  command: /bin/true
  notify: restart nginx
  when: ruby_version_changed | default( False )

- name: remove Bootsnap load path cache
  command: rm -r {{ project_app_root }}/tmp/cache/bootsnap-load-path-cache
  ignore_errors: True

- name: remove Bootsnap compile cache
  command: rm -r {{ project_app_root }}/tmp/cache/bootsnap-compile-cache
  ignore_errors: True